### ISSUE TITLE
[Question] PyTorch 1.11

### ISSUE THREAD

**Issue by austinmw** [pytorch/ort#112]
Hi, I see that the page https://onnxruntime.ai/ does not have PyTorch 1.10 or 1.11 as candidates. Is there any way to install torch-ort for latest PyTorch versions?

**Comment by baijumeswani** [comment]
That page needs to be updated. Please install the latest version of `torch_ort` and `onnxruntime-training` (version `1.11.1`). They should be compatible with both torch 1.10 and 1.11.

**Comment by baijumeswani** [comment]
Closing this issue. Let me know if you have more unanswered questions.
