### ISSUE TITLE
CUDA error cudaErrorInvalidConfiguration:invalid configuration argument

### ISSUE THREAD

**Issue by Suparjie** [pytorch/ort#116]
RuntimeError: Error in backward pass execution: Non-zero status code returned while running BiasGeluGrad_dX node. Name:'BiasGelu_token_112_Grad/BiasGeluGrad_dX_0' Status Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument

when I use a big tensor like (128, 3, 224, 224)，it will cause some errors.
If I change the tensor dimension to (16, 3, 224, 224), it works. So why?

**Comment by pengwa** [comment]
Thanks for reporting it, working on a fix now.

**Comment by pengwa** [comment]
@baijumeswani  please kindly help close this issue (seems I don't have permission for this one).
