### ISSUE TITLE
Will there be new nightly builds with version 1.13.0.dev? 

### ISSUE THREAD

**Issue by jambayk** [pytorch/ort#133]
Currently, the last nightly package on `https://download.onnxruntime.ai/torch_ort_nightly.html` is `torch_ort-1.12.0.dev20220719-py3-none-any.whl`. 

So, installing the nightly version of torch-ort with `python -m pip install --pre torch-ort -f https://download.onnxruntime.ai/torch_ort_nightly.html` just installs `torch-ort 1.12.0` from PyPI.  

Do you still plan to release nightly builds with updated versions?

**Comment by askhade** [comment]
Yes we do plan to release. Updates in progress.

**Comment by jambayk** [comment]
Thank you for the confirmation. I will close the issue then.
