### ISSUE TITLE
ORT support for CUDA 11.0

### ISSUE THREAD

**Issue by karthikrangasai** [pytorch/ort#93]
Hello all,

I am trying to use ORT on kaggle which currently has CUDA 11.0 but the current version available on `pip` is compatible with CUDA 10.2.

Is there support for CUDA 11.0 available from the master branch and if so how do I get it up and running ?

If the above is not the case, can the ORT team consider extending the compatibility ?

**Comment by natke** [comment]
Closing this issue as we believe it has been resolved. Please let us know if you run into any further issues.
