### ISSUE TITLE
torch_ort configure fails

### ISSUE THREAD

**Issue by wschin** [pytorch/ort#94]
Does anyone have a solution for the following error? I built ORT from source and got this error when installing torch_ort.

root@6fc16d770e85:/nfs# python -m torch_ort.configure
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/conda/lib/python3.8/runpy.py", line 111, in _get_module_details
   __import__(pkg_name)
  File "/opt/conda/lib/python3.8/site-packages/torch_ort/__init__.py", line 6, in <module>
    from onnxruntime.training.ortmodule import ORTModule, DebugOptions, LogLevel
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/__init__.py", line 34, in <module>
    raise import_capi_exception
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, \
ImportError: cannot import name 'enable_telemetry_events' from 'onnxruntime.capi._pybind_state' (/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/_pybind_state.py)

My build command is

```
./build.sh --config Debug  --enable_pybind --enable_language_interop_ops --use_cuda --enable_training --build_wheel --parallel --skip_tests --cuda_home /usr/local/cuda-11.1 --cudnn_home /usr/lib/x86_64-linux-gnu/ --cuda_version 11.1 --enable_training_torch_interop
```

torch_ort version: torch_ort in conda/lib/python3.8/site-packages (1.9.0)
ORT commit: 88d5023885ecfde70a5947a3247ab430f9270fb8 (Thu Oct 7 15:27:12 2021 -0700)

**Comment by kit1980** [comment]
Try do delete the existing build dir completely and rebuild from scratch.
I think there is an issue in dependency calculation somewhere in the build script, and sometimes changes in Python files are not updated.
